name: CI

on: [pull_request]

jobs:
  build:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Ti
        run: ./scripts/setup_ti.sh

      - name: Check plugin version
        run: ./scripts/check_version.sh

      - name: Build
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.PAT }}
        run: make build
