name: CI

on: [pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: actions/cache@v1
        with:
          path: ios/Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}

      - name: Setup Appcelerator
        run: ./scripts/setup_appc.sh ${{ secrets.APPC_USER_NAME }} ${{ secrets.APPC_PASSWORD }}

      - name: Check plugin version
        run: ./scripts/check_version.sh

      - name: Build
        run: make build

      - name: Upload iOS
        uses: actions/upload-artifact@v1
        with:
          name: ios
          path: ios/dist

     - name: Upload Android
        uses: actions/upload-artifact@v1
        with:
          name: android
          path: android/dist
